### ISSUE TITLE
Invalid options object.

### ISSUE THREAD

**Issue by tdrabikdev** [andyet/simplewebrtc-talky-sample-app#34]
Hello guys, i am really confused, I just cloned porject, i ran `npm install` - less more is installed. However when i want to build i am getting error
```
 webpack --mode production

Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
 - options.patterns[0] has an unknown property 'ignore'. These properties are valid:
   object { from, to?, context?, globOptions?, filter?, transformAll?, toType?, force?, priority?, info?, transform?, transformPath?, noErrorOnMissing? }
ValidationError: Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
    at validate (D:\projekty\simplewebrtc-talky-sample-app-master\node_modules\copy-webpack-plugin\node_modules\schema-utils\dist\validate.js:105:11)
    at new CopyPlugin (D:\projekty\simplewebrtc-talky-sample-app-master\node_modules\copy-webpack-plugin\dist\index.js:38:31)
    at Object.<anonymous> (D:\projekty\simplewebrtc-talky-sample-app-master\webpack.config.js:31:5)
    at Module._compile (D:\projekty\simplewebrtc-talky-sample-app-master\node_modules\webpack-cli\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (D:\projekty\simplewebrtc-talky-sample-app-master\node_modules\webpack-cli\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! simplewebrtc-demo-talky@1.0.0 build: `webpack --mode production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the simplewebrtc-demo-talky@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dev\AppData\Roaming\npm-cache\_logs\2021-08-28T17_36_32_815Z-debug.log
```

Any suggestion how it can be fixed?

**Comment by tdrabikdev** [comment]
Okay finally i run it.
